[package]
name = "winmon"
version = "0.1.0"
edition = "2024"

[dependencies.windows]
version = "0.61.1"
features = [
    "Win32_Storage_EnhancedStorage",
    "Win32_System_Com",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_UI_Shell_Common",
    "Win32_System_Time",
]
